// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing-layouts/CardStack.tsx": () => import("../components/mockups/landing-layouts/CardStack.tsx"),
  "./components/mockups/landing-layouts/CommandFirst.tsx": () => import("../components/mockups/landing-layouts/CommandFirst.tsx"),
  "./components/mockups/landing-layouts/SplitEdge.tsx": () => import("../components/mockups/landing-layouts/SplitEdge.tsx")
};
